### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getDataRange')

### ISSUE THREAD

**Issue by gokekun** [fmiccolis/GAS-conversational-telegram-bot#1]
Dear Mr. Miccolis,

I'm quite new to programming. I've been doing some JS and Python for the last year, but just very simple projects. It's possible that my issue is a very newbie issue, but I tried to check what I did wrong and I couldn't find:

I followed your setup instructions and tried to send a "/start" message to my bot. It replyed:

"TypeError: Cannot read properties of undefined (reading 'getDataRange')

{
  "update_id": xxxxxxxxxxx,
  "message": {
    "message_id": 7,
    "from": {
      "id": xxxxxxxxxxx,
      "is_bot": false,
      "first_name": "xxxxxxxxxxx",
      "last_name": "xxxxxxxxxxx",
      "username": "xxxxxxxxxxx",
      "language_code": "en"
    },
    "chat": {
      "id": xxxxxxxxxxx,
      "first_name": "xxxxxxxxxxx",
      "last_name": "xxxxxxxxxxx",
      "username": "xxxxxxxxxxx",
      "type": "private"
    },
    "date": 1684330590,
    "text": "/start"
  }
}
"

I checked my spreadsheet and the 3 tabs were created. But only the "received" and "sent" tab was filled with the message received and sent by the bot (because I didn't start a /conv"

After this first message, I tried to send another message, but the bot stopped answering. I tried a new deployment, but I stop answering.

**Comment by fmiccolis** [comment]
Hi Mr. Sugimoto,

First of all thanks for the star to the project, I appreciate it a lot!

I tried to replicate the problem and succeeded by running the function 'testFunction'. After that I sent the message /start to the bot and it responded correctly.
I will definitely have to update the code and documentation so that "testFunction" is the first function to be used immediately after the first deployment (Runned by hand in the Google App Script editor).
Regarding the bot's operation after subsequent deployments, would you point me to the steps you took?

For future communications, if you wish, you can call me by my first name at ease.

**Comment by gokekun** [comment]
Dear Francesco,

Thank you very much for your prompt reply.
Please also call me Felipe (and btw, despite my surname, I'm from
Brazil)(please forgive me for my poor english).

I tried the 'testFunction' and it worked to reset/boot the script, but
later I found that my issues were because of my foolish mistake.
Your instructions request:

*9. Click on "execute deployment" -> "new deployment" and choose "web app"
as type, "execute as me" and "everyone can access". Click on execute
deployment and keep from the result url the webAppId
(https://script.google.com/macros/s/*webAppId*/exec
<https://script.google.com/macros/s/*webAppId*/exec>)*


I was meant to get the 'webAppId' (Deployment ID) but I got the Web app
URL. I know that it's pretty obvious that it was the webAppId, 1st because
you said so, 2nd if you read the first lines of 1-Bot.gs you'll notice the "
this.webAppUrl = "https://script.google.com/macros/s/" + webAppId + "/exec";",
sorry for causing you trouble for such a fool mistake.

After I inserted the webAppId correctly, it worked flawlessly.

My bot is finally working. I could only achieved this project with your
implementation.

Thank you very much.

Best regards,

Felipe M. Sugimoto
+55 61 9 8116 6670  (*Whatsapp
<https://api.whatsapp.com/send?phone=5561981166670>/LINE*)
***@***.***
http://www.sugimoto.com.br

**Comment by fmiccolis** [comment]
Hi Felipe,

I am happy that you were able to solve the problem.
I have updated the documentation and a bit of the code to have a simpler and clearer bot start-up.

If you had not found the error on the .getDataRange() I could not have solved it so I thank you.

I hope your project continues smoothly, but if you need any help on how GAS-conversational-telegram-bot works, you can write to me by opening a new issue.
